name: My first Workflow

on: [push, pull_request]

jobs:
    say-hello:
        runs-on: ubuntu-latest

        steps:
            - name: Print message
              run: echo :hello, Github Actions!